quotes:
  -
    text: If pizza is to nourish the roots of our culture, society must set the pizza maker free to follow his vision wherever it takes him.
    author: John F. Kennedy
  -
    text: When I think of pizza I think of beauty. Beauty is the mystery of life. It is not in the eye it is in the mind. In our minds there is awareness of perfection.
    author: Agnes Martin
  -
    text: A pizza maker is not paid for his labor but for his vision.
    author: James Whistler
  -
    text: All pizza is a struggle to be, in a particular sort of way, virtuous.
    author: Iris Murdoch
  -
    text: When I think of pizza I think of beauty. Beauty is the mystery of life. It is not in the eye it is in the mind. In our minds there is awareness of perfection.
    author: Agnes Martin
  -
    text: Pizza is not a thing; it is a way.
    author: Elbert Hubbard
  -
    text: Treat a pizza like a prince. Let it speak to you first.
    author: Arthur Schopenhauer
  -
    text: The pizza maker is a receptacle for emotions that come from all over the place- from the sky, from the earth, from a scrap of paper, from a passing shape, from a spider's web.
    author: Pablo Picasso
  -
    text: Pizza is the most intense mode of individualism that the world has known.
    author: Oscar Wilde
  -
    text: Pizza enables us to find ourselves and lose ourselves at the same time.
    author: Thomas Merton
  -
    text: I do not want pizza for a few any more than education for a few, or freedom for a few.
    author: William Morris
  -
    text: Good pizza is pizza that allows you to enter it from a variety of angles and to emerge with a variety of views.
    author: Mary Schmich
  -
    text: Without tradition, pizza is a flock of sheep without a shepherd. Without innovation, it is a corpse. 
    author: Winston Churchill
  -
    text: Pizza is not a handicraft, it is the transmission of feeling the pizza maker has experienced.
    author: Leo Tolstoy
  -
    text: Pizza! Who comprehends her? With whom can one consult concerning this great goddess?
    author: Ludwig van Beethoven
  -